// Helpers for .github/workflows/review-relay.yml, called from
// actions/github-script steps. The workflow loads this file from a checkout
// of the default branch, never from the pull request under review.
//
// The relay's model turns only read files and return JSON. Everything that
// writes to GitHub is here, and it posts only what passes validate(): known
// comment IDs, changed paths, capped lengths, no @mentions.

'use strict';

const fs = require('fs');
const path = require('path');

const RELAY_MARKER = '<!-- review-relay:summary -->';
const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const MAX_ITEM_CHARS = 6000;
const MAX_BODY_CHARS = 4000;
const MAX_SUMMARY_CHARS = 20000;
const TRUSTED_ASSOCIATIONS = new Set(['OWNER', 'MEMBER', 'COLLABORATOR']);
// On a PR while turn 3 sees an open, unrefuted critical/high/medium finding,
// so it shows in the PR list before anyone merges.
const BLOCKING_LABEL = 'review-blocking';
const IMPACTS = ['breaking', 'adjacent', 'none', 'unclear'];

// A PR whose files all match this skips turns 2 and 3; turn 1 covers it.
const DOCS_ONLY = /(^docs\/)|(\.md$)/;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function headMarker(sha) {
  return `<!-- review-relay:head=${sha} -->`;
}

// Comments are read by a model, so drop what costs tokens and carries no
// review content (HTML comments, badges), then cap the length.
function clean(text) {
  if (!text) return '';
  let out = text.replace(/<!--[\s\S]*?-->/g, '').trim();
  if (out.length > MAX_ITEM_CHARS) {
    out = `${out.slice(0, MAX_ITEM_CHARS)}\n[… truncated by the relay]`;
  }
  return out;
}

// Break @mentions so a relay post never pings a person or summons a bot.
function defuse(text) {
  return String(text).replace(/@(?=[A-Za-z0-9])/g, '@​');
}

function cap(text, limit) {
  const s = String(text || '').trim();
  return s.length > limit ? `${s.slice(0, limit)}\n[… truncated]` : s;
}

// Only reviewers we installed or people with write access feed the model.
// Anyone else's comment on a public PR is left out of its context.
function trusted(association, isBot) {
  return isBot || TRUSTED_ASSOCIATIONS.has(association);
}

function quote(text) {
  return text
    .split('\n')
    .map((line) => `> ${line}`)
    .join('\n');
}

async function fetchThreads(github, owner, repo, pr) {
  const query = `
    query($owner: String!, $repo: String!, $pr: Int!, $cursor: String) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          reviewThreads(first: 50, after: $cursor) {
            pageInfo { hasNextPage endCursor }
            nodes {
              isResolved
              isOutdated
              path
              line
              originalLine
              comments(first: 50) {
                nodes {
                  databaseId
                  body
                  createdAt
                  authorAssociation
                  author { login __typename }
                }
              }
            }
          }
        }
      }
    }`;
  const threads = [];
  let cursor = null;
  for (;;) {
    const res = await github.graphql(query, { owner, repo, pr, cursor });
    const page = res.repository.pullRequest.reviewThreads;
    threads.push(...page.nodes);
    if (!page.pageInfo.hasNextPage) break;
    cursor = page.pageInfo.endCursor;
  }
  return threads;
}

async function findSticky(github, owner, repo, pr) {
  const comments = await github.paginate(github.rest.issues.listComments, {
    owner,
    repo,
    issue_number: pr,
    per_page: 100,
  });
  return comments.find(
    (c) => c.user && c.user.type === 'Bot' && (c.body || '').includes(RELAY_MARKER),
  );
}

// Decide whether the relay runs for this event, and wait for the review apps
// to finish so turn 2 can read them. Sets outputs: run, pr, head_sha, reason.
async function gate({ github, context, core }) {
  const { owner, repo } = context.repo;
  const env = process.env;
  const skip = (reason) => {
    core.info(`Relay skipped: ${reason}`);
    core.setOutput('run', 'false');
    core.setOutput('reason', reason);
  };

  let pr;
  let headSha;
  const force = env.RELAY_FORCE === 'true';
  if (context.eventName === 'workflow_dispatch') {
    pr = Number(env.RELAY_PR);
  } else {
    const run = context.payload.workflow_run;
    headSha = run.head_sha;
    pr = run.pull_requests && run.pull_requests[0] && run.pull_requests[0].number;
    if (!pr) {
      const assoc = await github.rest.repos.listPullRequestsAssociatedWithCommit({
        owner,
        repo,
        commit_sha: headSha,
      });
      const open = assoc.data.find((p) => p.state === 'open' && p.head.sha === headSha);
      pr = open && open.number;
    }
  }
  if (!pr) return skip('no open pull request for this run');

  const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  headSha = headSha || prData.head.sha;
  core.setOutput('pr', String(pr));
  core.setOutput('head_sha', headSha);

  if (prData.state !== 'open') return skip(`#${pr} is ${prData.state}`);
  if (prData.draft) return skip(`#${pr} is a draft`);
  if (prData.head.repo.full_name !== `${owner}/${repo}`) return skip('fork pull request');
  if (prData.head.sha !== headSha) return skip('a newer commit was pushed');

  const files = await github.paginate(github.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  if (files.length > 0 && files.every((f) => DOCS_ONLY.test(f.filename))) {
    return skip('docs-only change; the turn 1 audit covers it');
  }

  if (!force) {
    const sticky = await findSticky(github, owner, repo, pr);
    if (sticky && sticky.body.includes(headMarker(headSha))) {
      return skip(`the relay already ran for ${headSha.slice(0, 7)}`);
    }
  }

  const statuses = (env.RELAY_WAIT_STATUSES || '').split(',').map((s) => s.trim()).filter(Boolean);
  const reviewers = (env.RELAY_WAIT_REVIEWERS || '').split(',').map((s) => s.trim()).filter(Boolean);
  const deadline = Date.now() + Number(env.RELAY_MAX_WAIT_SECONDS || 600) * 1000;
  for (;;) {
    const { data: combined } = await github.rest.repos.getCombinedStatusForRef({
      owner,
      repo,
      ref: headSha,
    });
    const pendingStatuses = statuses.filter((name) => {
      const s = combined.statuses.find((st) => st.context === name);
      return !s || s.state === 'pending';
    });
    const reviews = await github.paginate(github.rest.pulls.listReviews, {
      owner,
      repo,
      pull_number: pr,
      per_page: 100,
    });
    // Some apps review only a PR's first commit. Wait for one only until it
    // has reviewed this PR once; after that, a later push won't bring it back.
    const pendingReviewers = reviewers.filter(
      (login) => !reviews.some((r) => r.user && r.user.login === login),
    );
    const pending = [...pendingStatuses, ...pendingReviewers];
    if (pending.length === 0) break;
    if (Date.now() > deadline) {
      core.warning(`Stopped waiting for: ${pending.join(', ')}`);
      break;
    }
    core.info(`Waiting for: ${pending.join(', ')}`);
    await sleep(30000);
  }

  const { data: latest } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  if (latest.head.sha !== headSha) return skip('a newer commit was pushed while waiting');

  core.setOutput('run', 'true');
  core.setOutput('reason', '');
  return undefined;
}

// Write relay/context.md, relay/pr.diff and relay/known.json for a model turn.
// Sets output open_threads (unresolved, not outdated review threads).
async function collect({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const outDir = path.join(process.env.GITHUB_WORKSPACE, 'relay');
  fs.mkdirSync(outDir, { recursive: true });

  const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  const files = await github.paginate(github.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  let diff;
  try {
    const res = await github.rest.pulls.get({
      owner,
      repo,
      pull_number: pr,
      mediaType: { format: 'diff' },
    });
    diff = res.data;
  } catch (err) {
    diff = `The diff is not available from the API (${err.message}). Read the changed files under pr/ instead.\n`;
  }
  const issueComments = await github.paginate(github.rest.issues.listComments, {
    owner,
    repo,
    issue_number: pr,
    per_page: 100,
  });
  const reviews = await github.paginate(github.rest.pulls.listReviews, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  const threads = await fetchThreads(github, owner, repo, pr);

  const lines = [];
  const commentIds = [];
  const roots = {};
  let openThreads = 0;
  let omitted = 0;

  lines.push(`# PR #${pr}: ${prData.title}`, '');
  lines.push(`Author: ${prData.user.login}. Base: ${prData.base.ref}. Head: ${headSha}.`, '');
  lines.push('## Description', '', clean(prData.body) || '(none)', '');
  lines.push(`## Changed files (${files.length})`, '');
  for (const f of files) lines.push(`- ${f.filename} (${f.status}, +${f.additions} -${f.deletions})`);
  lines.push('');

  lines.push('## Review threads', '');
  threads.forEach((t, i) => {
    const state = t.isResolved ? 'resolved' : t.isOutdated ? 'outdated' : 'open';
    if (state === 'open') openThreads += 1;
    const where = `${t.path}:${t.line || t.originalLine || '?'}`;
    const shown = t.comments.nodes.filter((c) =>
      trusted(c.authorAssociation, c.author && c.author.__typename === 'Bot'),
    );
    omitted += t.comments.nodes.length - shown.length;
    if (shown.length === 0) return;
    lines.push(`### Thread ${i + 1}: ${where} (${state})`, '');
    for (const c of shown) {
      if (state === 'open') {
        commentIds.push(c.databaseId);
        // GitHub accepts replies only to a thread's first comment.
        roots[c.databaseId] = t.comments.nodes[0].databaseId;
      }
      const who = c.author ? c.author.login : 'ghost';
      lines.push(`[comment_id ${c.databaseId}] ${who}, ${c.createdAt}:`, '', quote(clean(c.body)), '');
    }
  });

  lines.push('## Reviews', '');
  for (const r of reviews) {
    if (!trusted(r.author_association, r.user && r.user.type === 'Bot')) {
      omitted += 1;
      continue;
    }
    const body = clean(r.body);
    if (!body) continue;
    const who = r.user ? r.user.login : 'ghost';
    lines.push(`### ${who}: ${r.state} on ${(r.commit_id || '').slice(0, 7)}, ${r.submitted_at}`, '', quote(body), '');
  }

  lines.push('## Conversation', '');
  for (const c of issueComments) {
    if (!trusted(c.author_association, c.user && c.user.type === 'Bot')) {
      omitted += 1;
      continue;
    }
    const who = c.user ? c.user.login : 'ghost';
    lines.push(`### ${who}, ${c.created_at}`, '', quote(clean(c.body)), '');
  }
  if (omitted > 0) {
    lines.push(`(${omitted} comments from accounts without write access were left out.)`, '');
  }

  fs.writeFileSync(path.join(outDir, 'context.md'), lines.join('\n'));
  fs.writeFileSync(path.join(outDir, 'pr.diff'), diff);
  fs.writeFileSync(
    path.join(outDir, 'known.json'),
    JSON.stringify({ comment_ids: commentIds, roots, paths: files.map((f) => f.filename) }),
  );
  core.setOutput('open_threads', String(openThreads));
  core.info(`Collected ${threads.length} threads (${openThreads} open), ${reviews.length} reviews, ${issueComments.length} comments.`);
}

// Keep only what may be posted: replies to known open-thread comments,
// findings on changed paths, bounded counts and lengths.
function validate(output, known, { maxReplies, maxFindings }) {
  const ids = new Set(known.comment_ids);
  const paths = new Set(known.paths);
  const replies = (output.replies || [])
    .filter((r) => Number.isInteger(r.comment_id) && ids.has(r.comment_id) && String(r.body || '').trim())
    .slice(0, maxReplies)
    .map((r) => ({
      comment_id: r.comment_id,
      root_id: (known.roots && known.roots[r.comment_id]) || r.comment_id,
      body: defuse(cap(r.body, MAX_BODY_CHARS)),
    }));
  const agree = [...new Set((output.agree || []).filter((id) => Number.isInteger(id) && ids.has(id)))];
  const findings = (output.new_findings || [])
    .filter((f) => paths.has(f.path) && Number.isInteger(f.line) && f.line > 0 && String(f.body || '').trim())
    .slice(0, maxFindings)
    .map((f) => ({
      path: f.path,
      line: f.line,
      severity: ['critical', 'high', 'medium', 'low'].includes(f.severity) ? f.severity : 'low',
      body: defuse(cap(f.body, MAX_BODY_CHARS)),
    }));
  return { replies, agree, findings };
}

// Low findings read as nits, kept apart from logic objections.
function tag(severity) {
  return severity === 'low' ? 'nit: ' : `[${severity}] `;
}

async function setBlockingLabel(github, core, owner, repo, pr, blocking) {
  try {
    if (blocking) {
      await github.rest.issues.addLabels({ owner, repo, issue_number: pr, labels: [BLOCKING_LABEL] });
    } else {
      await github.rest.issues.removeLabel({ owner, repo, issue_number: pr, name: BLOCKING_LABEL });
    }
  } catch (err) {
    // removeLabel 404s when the label isn't on the PR; neither case should
    // fail the run.
    if (blocking || err.status !== 404) core.warning(`Could not update the ${BLOCKING_LABEL} label: ${err.message}`);
  }
}

function readTurn(env) {
  const known = JSON.parse(
    fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'relay', 'known.json'), 'utf8'),
  );
  let output = {};
  try {
    output = JSON.parse(env || '{}');
  } catch (err) {
    throw new Error(`The model turn did not return valid JSON: ${err.message}`);
  }
  return { known, output };
}

async function postReplies(github, owner, repo, pr, label, replies) {
  let posted = 0;
  for (const r of replies) {
    await github.rest.pulls.createReplyForReviewComment({
      owner,
      repo,
      pull_number: pr,
      comment_id: r.root_id,
      body: `**Review relay · ${label}**\n\n${r.body}${FOOTER}`,
    });
    posted += 1;
  }
  return posted;
}

// Turn 2: reply in threads, 👍 the findings it confirms, and post its own
// findings as one review. Sets output summary for turn 3.
async function postTurn2({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const { known, output } = readTurn(process.env.RELAY_OUTPUT);
  const { replies, agree, findings } = validate(output, known, { maxReplies: 5, maxFindings: 5 });
  const label = 'turn 2 (second opinion)';

  const posted = await postReplies(github, owner, repo, pr, label, replies);
  for (const id of agree) {
    await github.rest.reactions.createForPullRequestReviewComment({
      owner,
      repo,
      comment_id: id,
      content: '+1',
    });
  }

  let inline = 0;
  if (findings.length > 0) {
    const summary = defuse(cap(output.summary, MAX_BODY_CHARS));
    const heading = `**Review relay · ${label}**: ${findings.length} finding(s) the other reviewers did not raise.\n\n${summary}`;
    try {
      await github.rest.pulls.createReview({
        owner,
        repo,
        pull_number: pr,
        commit_id: headSha,
        event: 'COMMENT',
        body: `${heading}${FOOTER}`,
        comments: findings.map((f) => ({
          path: f.path,
          line: f.line,
          side: 'RIGHT',
          body: `${tag(f.severity)}${f.body}`,
        })),
      });
      inline = findings.length;
    } catch (err) {
      // A line outside the diff makes GitHub reject the whole review; post
      // the findings as one comment instead of losing them.
      core.warning(`Inline review failed (${err.message}); posting the findings as a comment.`);
      const list = findings.map((f) => `- ${tag(f.severity)}\`${f.path}:${f.line}\`: ${f.body}`).join('\n');
      await github.rest.issues.createComment({
        owner,
        repo,
        issue_number: pr,
        body: `${heading}\n\n${list}${FOOTER}`,
      });
    }
  }

  const summary = cap(output.summary, MAX_BODY_CHARS);
  core.setOutput('summary', summary);
  core.setOutput('activity', String(posted + findings.length));
  core.info(`Turn 2: ${posted} replies, ${agree.length} agreements, ${findings.length} findings (${inline} inline).`);
}

// Turn 3: settle disagreements in their threads and keep one summary comment
// per PR, edited in place. With no model output, records that nothing is open.
async function postTurn3({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const ranModel = Boolean(process.env.RELAY_OUTPUT);
  const { known, output } = readTurn(process.env.RELAY_OUTPUT);

  let replies = [];
  let state;
  const blocking = ranModel && output.blocking === true;
  if (ranModel) {
    replies = validate(output, known, { maxReplies: 3, maxFindings: 0 }).replies;
    const impact = IMPACTS.includes(output.consensus_impact) ? output.consensus_impact : 'unclear';
    state = [
      `**Blocking:** ${blocking ? 'yes, an open critical, high or medium finding is not refuted' : 'no'}`,
      `**Consensus impact:** ${impact}`,
      `**Determinism:** ${defuse(cap(output.determinism, 600)) || 'not assessed'}`,
      '',
      defuse(cap(output.summary_markdown, MAX_SUMMARY_CHARS)),
    ].join('\n');
  } else {
    state = '**Blocking:** no\n\nNo review thread is open and turn 2 added nothing, so the moderator did not run. See the turn 1 audit for the consensus-impact verdict.';
  }
  await setBlockingLabel(github, core, owner, repo, pr, blocking);
  const posted = await postReplies(github, owner, repo, pr, 'turn 3 (moderator)', replies);

  const turn2 = cap(process.env.RELAY_TURN2_SUMMARY, MAX_BODY_CHARS);
  const body = [
    RELAY_MARKER,
    headMarker(headSha),
    '## Review relay: state of the review',
    '',
    `_As of \`${headSha.slice(0, 7)}\`. Turn 1 is the Claude audit; turn 2 a second opinion that reads every reviewer; turn 3 this summary. It is edited in place on each push._`,
    '',
    state,
    turn2 ? `\n<details><summary>Turn 2 (second opinion)</summary>\n\n${defuse(turn2)}\n\n</details>` : '',
    '',
    '_The relay reports findings; it does not approve. The merge decision is the maintainer\'s._',
    FOOTER,
  ].join('\n');

  const sticky = await findSticky(github, owner, repo, pr);
  if (sticky) {
    await github.rest.issues.updateComment({ owner, repo, comment_id: sticky.id, body });
  } else {
    await github.rest.issues.createComment({ owner, repo, issue_number: pr, body });
  }
  core.info(`Turn 3: ${posted} replies; summary ${sticky ? 'updated' : 'created'}.`);
}

module.exports = { gate, collect, postTurn2, postTurn3, validate, clean, defuse, trusted, tag, DOCS_ONLY };
