// Helpers for .github/workflows/review-relay.yml, called from
// actions/github-script steps. The workflow loads this file from a checkout
// of the default branch, never from the pull request under review.
//
// The relay's model turns only read files and return JSON. Everything that
// writes to GitHub is here, and it posts only what passes validate(): known
// comment IDs, lines inside the diff, capped lengths, no @mentions. Every
// posting step first checks that the PR head is still the commit reviewed.

'use strict';

const fs = require('fs');
const path = require('path');

const RELAY_MARKER = '<!-- review-relay:summary -->';
const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const MAX_ITEM_CHARS = 6000;
const MAX_BODY_CHARS = 4000;
const MAX_SUMMARY_CHARS = 20000;
// Review apps whose comments the models may read. Anyone else must have
// write access to the repository.
const DEFAULT_TRUSTED_BOTS = 'claude,coderabbitai,greptile-apps,devin-ai-integration,github-actions';
const WRITE_PERMISSIONS = new Set(['admin', 'maintain', 'write']);
// On a PR while turn 3 sees an open, unrefuted critical/high/medium finding,
// so it shows in the PR list before anyone merges.
const BLOCKING_LABEL = 'review-blocking';
const IMPACTS = ['breaking', 'adjacent', 'none', 'unclear'];
// Commit status the relay sets on the PR head. Add it to the ruleset's
// required checks to make GO a merge requirement.
const CONSENSUS_CONTEXT = 'Review consensus';
// A maintainer's label that turns the status green whatever the verdict.
const OVERRIDE_LABEL = 'consensus-override';
const VERDICTS = ['GO', 'NO-GO', 'NONE'];

// A PR whose files all match this skips turns 2 and 3; turn 1 covers it.
const DOCS_ONLY = /(^docs\/)|(\.md$)/;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function headMarker(sha) {
  return `<!-- review-relay:head=${sha} -->`;
}

// Comments are read by a model, so drop what costs tokens and carries no
// review content (HTML comments, badges), then cap the length.
function clean(text) {
  if (!text) return '';
  let out = text.replace(/<!--[\s\S]*?-->/g, '').trim();
  if (out.length > MAX_ITEM_CHARS) {
    out = `${out.slice(0, MAX_ITEM_CHARS)}\n[… truncated by the relay]`;
  }
  return out;
}

// Break @mentions so a relay post never pings a person or summons a bot.
function defuse(text) {
  return String(text).replace(/@(?=[A-Za-z0-9])/g, '@​');
}

function cap(text, limit) {
  const s = String(text || '').trim();
  return s.length > limit ? `${s.slice(0, limit)}\n[… truncated]` : s;
}

function botName(login) {
  return String(login || '').toLowerCase().replace(/\[bot\]$/, '');
}

// Only listed review apps and people with write access feed the model.
// Anyone else's comment on a public PR is left out of its context. An
// author's association (MEMBER, COLLABORATOR) doesn't imply write access,
// so the permission is looked up, once per login.
function makeTrust(github, owner, repo) {
  const bots = new Set(
    (process.env.RELAY_TRUSTED_BOTS || DEFAULT_TRUSTED_BOTS).split(',').map(botName).filter(Boolean),
  );
  const cache = new Map();
  return async (login, isBot) => {
    if (!login) return false;
    if (isBot) return bots.has(botName(login));
    if (!cache.has(login)) {
      cache.set(
        login,
        github.rest.repos
          .getCollaboratorPermissionLevel({ owner, repo, username: login })
          .then((res) => WRITE_PERMISSIONS.has(res.data.permission) || WRITE_PERMISSIONS.has(res.data.role_name))
          .catch(() => false),
      );
    }
    return cache.get(login);
  };
}

// Lines on the new side of a file's diff (added or context): the only lines
// GitHub accepts an inline comment on.
function rightLines(patch) {
  const out = [];
  let n = 0;
  for (const l of String(patch || '').split('\n')) {
    const hunk = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(l);
    if (hunk) {
      n = Number(hunk[1]);
      continue;
    }
    if (!n || l.startsWith('-') || l.startsWith('\\')) continue;
    out.push(n);
    n += 1;
  }
  return out;
}

async function headMoved(github, owner, repo, pr, sha) {
  const { data } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  return data.head.sha !== sha;
}

function quote(text) {
  return text
    .split('\n')
    .map((line) => `> ${line}`)
    .join('\n');
}

async function fetchThreads(github, owner, repo, pr) {
  const query = `
    query($owner: String!, $repo: String!, $pr: Int!, $cursor: String) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          reviewThreads(first: 50, after: $cursor) {
            pageInfo { hasNextPage endCursor }
            nodes {
              isResolved
              isOutdated
              path
              line
              originalLine
              root: comments(first: 1) { nodes { ...c } }
              latest: comments(last: 49) { totalCount nodes { ...c } }
            }
          }
        }
      }
    }
    fragment c on PullRequestReviewComment {
      databaseId
      body
      createdAt
      author { login __typename }
    }`;
  const threads = [];
  let cursor = null;
  for (;;) {
    const res = await github.graphql(query, { owner, repo, pr, cursor });
    const page = res.repository.pullRequest.reviewThreads;
    // A thread's first comment (replies go to it) and its latest 49, so a
    // long thread still shows the most recent fix or retraction.
    for (const t of page.nodes) {
      const seen = new Set();
      const nodes = [...t.root.nodes, ...t.latest.nodes].filter((c) => !seen.has(c.databaseId) && seen.add(c.databaseId));
      threads.push({ ...t, comments: { nodes, skipped: t.latest.totalCount - nodes.length } });
    }
    if (!page.pageInfo.hasNextPage) break;
    cursor = page.pageInfo.endCursor;
  }
  return threads;
}

async function findSticky(github, owner, repo, pr) {
  const comments = await github.paginate(github.rest.issues.listComments, {
    owner,
    repo,
    issue_number: pr,
    per_page: 100,
  });
  return comments.find(
    (c) => c.user && c.user.type === 'Bot' && (c.body || '').includes(RELAY_MARKER),
  );
}

// Decide whether the relay runs for this event, and wait for the review apps
// to finish so turn 2 can read them. Sets outputs: run, pr, head_sha, reason.
async function gate({ github, context, core }) {
  const { owner, repo } = context.repo;
  const env = process.env;
  const skip = (reason) => {
    core.info(`Relay skipped: ${reason}`);
    core.setOutput('run', 'false');
    core.setOutput('reason', reason);
  };

  let pr;
  let headSha;
  const force = env.RELAY_FORCE === 'true';
  if (context.eventName === 'workflow_dispatch') {
    pr = Number(env.RELAY_PR);
  } else {
    const run = context.payload.workflow_run;
    headSha = run.head_sha;
    pr = run.pull_requests && run.pull_requests[0] && run.pull_requests[0].number;
    if (!pr) {
      const assoc = await github.rest.repos.listPullRequestsAssociatedWithCommit({
        owner,
        repo,
        commit_sha: headSha,
      });
      const open = assoc.data.find((p) => p.state === 'open' && p.head.sha === headSha);
      pr = open && open.number;
    }
  }
  if (!pr) return skip('no open pull request for this run');

  const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  headSha = headSha || prData.head.sha;
  core.setOutput('pr', String(pr));
  core.setOutput('head_sha', headSha);

  if (prData.state !== 'open') return skip(`#${pr} is ${prData.state}`);
  if (prData.draft) return skip(`#${pr} is a draft`);
  if (prData.head.repo.full_name !== `${owner}/${repo}`) return skip('fork pull request');
  if (prData.head.sha !== headSha) return skip('a newer commit was pushed');

  const files = await github.paginate(github.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  if (files.length > 0 && files.every((f) => DOCS_ONLY.test(f.filename))) {
    await setConsensus(github, owner, repo, headSha, 'success', 'Docs-only change: the turn 1 audit covers it');
    return skip('docs-only change; the turn 1 audit covers it');
  }

  if (!force) {
    const sticky = await findSticky(github, owner, repo, pr);
    if (sticky && sticky.body.includes(headMarker(headSha))) {
      return skip(`the relay already ran for ${headSha.slice(0, 7)}`);
    }
  }

  const statuses = (env.RELAY_WAIT_STATUSES || '').split(',').map((s) => s.trim()).filter(Boolean);
  const reviewers = (env.RELAY_WAIT_REVIEWERS || '').split(',').map((s) => s.trim()).filter(Boolean);
  const deadline = Date.now() + Number(env.RELAY_MAX_WAIT_SECONDS || 600) * 1000;
  for (;;) {
    const { data: combined } = await github.rest.repos.getCombinedStatusForRef({
      owner,
      repo,
      ref: headSha,
    });
    const pendingStatuses = statuses.filter((name) => {
      const s = combined.statuses.find((st) => st.context === name);
      return !s || s.state === 'pending';
    });
    const reviews = await github.paginate(github.rest.pulls.listReviews, {
      owner,
      repo,
      pull_number: pr,
      per_page: 100,
    });
    // Some apps review only a PR's first commit. Wait for one only until it
    // has reviewed this PR once; after that, a later push won't bring it back.
    const pendingReviewers = reviewers.filter(
      (login) => !reviews.some((r) => r.user && r.user.login === login),
    );
    const pending = [...pendingStatuses, ...pendingReviewers];
    if (pending.length === 0) break;
    if (Date.now() > deadline) {
      core.warning(`Stopped waiting for: ${pending.join(', ')}`);
      break;
    }
    core.info(`Waiting for: ${pending.join(', ')}`);
    await sleep(30000);
  }

  const { data: latest } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  if (latest.head.sha !== headSha) return skip('a newer commit was pushed while waiting');

  await setRelayStatus(github, owner, repo, pr, headSha, 'pending', 'Review relay running');
  core.setOutput('run', 'true');
  core.setOutput('reason', '');
  return undefined;
}

// Write relay/context.md, relay/pr.diff and relay/known.json for a model turn.
// Sets output open_threads (unresolved, not outdated review threads).
async function collect({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const outDir = path.join(process.env.GITHUB_WORKSPACE, 'relay');
  fs.mkdirSync(outDir, { recursive: true });

  const { data: prData } = await github.rest.pulls.get({ owner, repo, pull_number: pr });
  if (prData.head.sha !== headSha) {
    core.info(`A newer commit (${prData.head.sha.slice(0, 7)}) was pushed; this relay run stops.`);
    core.setOutput('stale', 'true');
    return;
  }
  core.setOutput('stale', 'false');
  const trust = makeTrust(github, owner, repo);
  const files = await github.paginate(github.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  let diff;
  try {
    const res = await github.rest.pulls.get({
      owner,
      repo,
      pull_number: pr,
      mediaType: { format: 'diff' },
    });
    diff = res.data;
  } catch (err) {
    diff = `The diff is not available from the API (${err.message}). Read the changed files under pr/ instead.\n`;
  }
  const issueComments = await github.paginate(github.rest.issues.listComments, {
    owner,
    repo,
    issue_number: pr,
    per_page: 100,
  });
  const reviews = await github.paginate(github.rest.pulls.listReviews, {
    owner,
    repo,
    pull_number: pr,
    per_page: 100,
  });
  const threads = await fetchThreads(github, owner, repo, pr);

  const lines = [];
  const commentIds = [];
  const roots = {};
  let openThreads = 0;
  let omitted = 0;

  lines.push(`# PR #${pr}: ${prData.title}`, '');
  lines.push(`Author: ${prData.user.login}. Base: ${prData.base.ref}. Head: ${headSha}.`, '');
  lines.push('## Description', '', clean(prData.body) || '(none)', '');
  lines.push(`## Changed files (${files.length})`, '');
  for (const f of files) lines.push(`- ${f.filename} (${f.status}, +${f.additions} -${f.deletions})`);
  lines.push('');

  lines.push('## Review threads', '');
  for (const [i, t] of threads.entries()) {
    const state = t.isResolved ? 'resolved' : t.isOutdated ? 'outdated' : 'open';
    if (state === 'open') openThreads += 1;
    const where = `${t.path}:${t.line || t.originalLine || '?'}`;
    const shown = [];
    for (const c of t.comments.nodes) {
      if (await trust(c.author && c.author.login, c.author && c.author.__typename === 'Bot')) shown.push(c);
    }
    omitted += t.comments.nodes.length - shown.length;
    if (shown.length === 0) continue;
    lines.push(`### Thread ${i + 1}: ${where} (${state})`, '');
    if (t.comments.skipped > 0) lines.push(`(${t.comments.skipped} earlier replies not shown.)`, '');
    for (const c of shown) {
      if (state === 'open') {
        commentIds.push(c.databaseId);
        // GitHub accepts replies only to a thread's first comment.
        roots[c.databaseId] = t.comments.nodes[0].databaseId;
      }
      const who = c.author ? c.author.login : 'ghost';
      lines.push(`[comment_id ${c.databaseId}] ${who}, ${c.createdAt}:`, '', quote(clean(c.body)), '');
    }
  }

  lines.push('## Reviews', '');
  for (const r of reviews) {
    if (!(await trust(r.user && r.user.login, r.user && r.user.type === 'Bot'))) {
      omitted += 1;
      continue;
    }
    const body = clean(r.body);
    if (!body) continue;
    const who = r.user ? r.user.login : 'ghost';
    lines.push(`### ${who}: ${r.state} on ${(r.commit_id || '').slice(0, 7)}, ${r.submitted_at}`, '', quote(body), '');
  }

  lines.push('## Conversation', '');
  for (const c of issueComments) {
    if (!(await trust(c.user && c.user.login, c.user && c.user.type === 'Bot'))) {
      omitted += 1;
      continue;
    }
    const who = c.user ? c.user.login : 'ghost';
    lines.push(`### ${who}, ${c.created_at}`, '', quote(clean(c.body)), '');
  }
  if (omitted > 0) {
    lines.push(`(${omitted} comments from accounts without write access, or from unlisted apps, were left out.)`, '');
  }

  fs.writeFileSync(path.join(outDir, 'context.md'), lines.join('\n'));
  fs.writeFileSync(path.join(outDir, 'pr.diff'), diff);
  fs.writeFileSync(
    path.join(outDir, 'known.json'),
    JSON.stringify({
      comment_ids: commentIds,
      roots,
      // null: GitHub sent no patch (large or binary file), so lines can't be
      // checked; findings there are posted as a comment, not inline.
      lines: Object.fromEntries(files.map((f) => [f.filename, f.patch ? rightLines(f.patch) : null])),
    }),
  );
  core.setOutput('open_threads', String(openThreads));
  core.info(`Collected ${threads.length} threads (${openThreads} open), ${reviews.length} reviews, ${issueComments.length} comments.`);
}

// Keep only what may be posted: replies to known open-thread comments,
// findings on changed files, inline only on lines inside the diff, bounded
// counts and lengths.
function validate(output, known, { maxReplies, maxFindings }) {
  const ids = new Set(known.comment_ids);
  const fileLines = known.lines || {};
  // true: inline on a diff line; false: changed file without a patch; null: reject.
  const placement = (p, line) => {
    if (!Object.prototype.hasOwnProperty.call(fileLines, p)) return null;
    if (fileLines[p] === null) return false;
    return fileLines[p].includes(line) ? true : null;
  };
  const replies = (output.replies || [])
    .filter((r) => Number.isInteger(r.comment_id) && ids.has(r.comment_id) && String(r.body || '').trim())
    .slice(0, maxReplies)
    .map((r) => ({
      comment_id: r.comment_id,
      root_id: (known.roots && known.roots[r.comment_id]) || r.comment_id,
      body: defuse(cap(r.body, MAX_BODY_CHARS)),
    }));
  const agree = [...new Set((output.agree || []).filter((id) => Number.isInteger(id) && ids.has(id)))];
  const findings = (output.new_findings || [])
    .filter((f) => Number.isInteger(f.line) && f.line > 0 && placement(f.path, f.line) !== null && String(f.body || '').trim())
    .slice(0, maxFindings)
    .map((f) => ({
      path: f.path,
      line: f.line,
      inline: placement(f.path, f.line),
      severity: ['critical', 'high', 'medium', 'low'].includes(f.severity) ? f.severity : 'low',
      body: defuse(cap(f.body, MAX_BODY_CHARS)),
    }));
  return { replies, agree, findings };
}

// Low findings read as nits, kept apart from logic objections.
function tag(severity) {
  return severity === 'low' ? 'nit: ' : `[${severity}] `;
}

// Creates the label the first time it is needed. A failure here fails the
// job, so a missing label is visible rather than silent.
async function setBlockingLabel(github, owner, repo, pr, blocking) {
  if (blocking) {
    try {
      await github.rest.issues.getLabel({ owner, repo, name: BLOCKING_LABEL });
    } catch (err) {
      if (err.status !== 404) throw err;
      await github.rest.issues.createLabel({
        owner,
        repo,
        name: BLOCKING_LABEL,
        color: 'b60205',
        description: 'Review relay: an open critical, high or medium finding is not refuted',
      });
    }
    await github.rest.issues.addLabels({ owner, repo, issue_number: pr, labels: [BLOCKING_LABEL] });
    return;
  }
  try {
    await github.rest.issues.removeLabel({ owner, repo, issue_number: pr, name: BLOCKING_LABEL });
  } catch (err) {
    if (err.status !== 404) throw err; // 404: the label wasn't on the PR
  }
}

function runUrl() {
  const { GITHUB_SERVER_URL: server, GITHUB_REPOSITORY: repo, GITHUB_RUN_ID: run } = process.env;
  return server && repo && run ? `${server}/${repo}/actions/runs/${run}` : undefined;
}

async function setConsensus(github, owner, repo, sha, state, description) {
  await github.rest.repos.createCommitStatus({
    owner,
    repo,
    sha,
    state,
    context: CONSENSUS_CONTEXT,
    description: description.slice(0, 140),
    target_url: runUrl(),
  });
}

async function hasOverride(github, owner, repo, pr) {
  const { data } = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number: pr, per_page: 100 });
  return data.some((l) => l.name === OVERRIDE_LABEL);
}

// Every status the relay itself writes goes through here, so it never
// replaces a maintainer's override: with the label on, it writes success.
// It checks again after writing, because the label's own workflow may have
// posted success while this write was in flight; the last write then
// still ends green.
async function setRelayStatus(github, owner, repo, pr, sha, state, description) {
  if (await hasOverride(github, owner, repo, pr)) {
    await setConsensus(github, owner, repo, sha, 'success', `Overridden by label (relay: ${description})`);
    return true;
  }
  await setConsensus(github, owner, repo, sha, state, description);
  if (state !== 'success' && (await hasOverride(github, owner, repo, pr))) {
    await setConsensus(github, owner, repo, sha, 'success', `Overridden by label (relay: ${description})`);
    return true;
  }
  return false;
}

async function docsOnly(github, owner, repo, pr) {
  const files = await github.paginate(github.rest.pulls.listFiles, { owner, repo, pull_number: pr, per_page: 100 });
  return files.length > 0 && files.every((f) => DOCS_ONLY.test(f.filename));
}

// GO only when no reviewer's NO-GO stands (unrefuted) and at least
// RELAY_MIN_GO reviewers said GO. One reviewer can block; none can pass a
// PR alone.
function tally(verdicts, minGo) {
  const standing = verdicts.filter((v) => v.verdict === 'NO-GO' && !v.refuted);
  const gos = verdicts.filter((v) => v.verdict === 'GO');
  if (standing.length > 0) {
    return { consensus: 'NO-GO', standing, gos, why: `${standing.length} standing NO-GO (${standing.map((v) => v.reviewer).join(', ')})` };
  }
  if (gos.length < minGo) {
    return { consensus: 'NO-GO', standing, gos, why: `only ${gos.length} GO verdict(s); ${minGo} needed` };
  }
  return { consensus: 'GO', standing, gos, why: `${gos.length} GO, no standing NO-GO` };
}

function cell(text) {
  return defuse(cap(text, 300)).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function readTurn(env, turn) {
  if (!env) {
    // The model step succeeded but returned nothing: fail, so the relay isn't
    // green while the PR's summary still describes an older review.
    throw new Error(`${turn} returned no structured output; nothing was posted and the summary and label are unchanged.`);
  }
  const known = JSON.parse(
    fs.readFileSync(path.join(process.env.GITHUB_WORKSPACE, 'relay', 'known.json'), 'utf8'),
  );
  let output;
  try {
    output = JSON.parse(env);
  } catch (err) {
    throw new Error(`The model turn did not return valid JSON: ${err.message}`);
  }
  return { known, output };
}

async function postReplies(github, owner, repo, pr, label, replies) {
  let posted = 0;
  for (const r of replies) {
    await github.rest.pulls.createReplyForReviewComment({
      owner,
      repo,
      pull_number: pr,
      comment_id: r.root_id,
      body: `**Review relay · ${label}**\n\n${r.body}${FOOTER}`,
    });
    posted += 1;
  }
  return posted;
}

// Turn 2: reply in threads, 👍 the findings it confirms, and post its own
// findings as one review. Sets output summary for turn 3.
async function postTurn2({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const { known, output } = readTurn(process.env.RELAY_OUTPUT, 'Turn 2');
  const { replies, agree, findings } = validate(output, known, { maxReplies: 5, maxFindings: 5 });
  const label = 'turn 2 (second opinion)';
  if (await headMoved(github, owner, repo, pr, headSha)) {
    core.info('A newer commit was pushed; turn 2 posts nothing for the old one.');
    core.setOutput('summary', '');
    core.setOutput('activity', '0');
    return;
  }

  const posted = await postReplies(github, owner, repo, pr, label, replies);
  for (const id of agree) {
    await github.rest.reactions.createForPullRequestReviewComment({
      owner,
      repo,
      comment_id: id,
      content: '+1',
    });
  }

  let inline = 0;
  if (findings.length > 0) {
    const summary = defuse(cap(output.summary, MAX_BODY_CHARS));
    const heading = `**Review relay · ${label}**: ${findings.length} finding(s) the other reviewers did not raise.\n\n${summary}`;
    const onDiff = findings.filter((f) => f.inline);
    let asComment = findings.filter((f) => !f.inline);
    if (onDiff.length > 0) {
      try {
        await github.rest.pulls.createReview({
          owner,
          repo,
          pull_number: pr,
          commit_id: headSha,
          event: 'COMMENT',
          body: `${heading}${FOOTER}`,
          comments: onDiff.map((f) => ({
            path: f.path,
            line: f.line,
            side: 'RIGHT',
            body: `${tag(f.severity)}${f.body}`,
          })),
        });
        inline = onDiff.length;
      } catch (err) {
        // validate() keeps inline findings on diff lines, so this is rare
        // (e.g. the API rejecting the review); post them as a comment instead.
        core.warning(`Inline review failed (${err.message}); posting the findings as a comment.`);
        asComment = findings;
      }
    }
    // Findings on files GitHub sent no patch for (or that the inline review
    // couldn't take) go in one comment.
    if (asComment.length > 0) {
      const list = asComment.map((f) => `- ${tag(f.severity)}\`${f.path}:${f.line}\`: ${f.body}`).join('\n');
      await github.rest.issues.createComment({
        owner,
        repo,
        issue_number: pr,
        body: `${inline ? `**Review relay · ${label}**: findings on files without a diff from the API.` : heading}\n\n${list}${FOOTER}`,
      });
    }
  }

  const summary = cap(output.summary, MAX_BODY_CHARS);
  core.setOutput('summary', summary);
  core.setOutput('verdict', ['GO', 'NO-GO'].includes(output.verdict) ? output.verdict : 'NONE');
  core.setOutput('activity', String(posted + findings.length));
  core.info(`Turn 2: ${posted} replies, ${agree.length} agreements, ${findings.length} findings (${inline} inline).`);
}

// Turn 3: settle disagreements in their threads, tally each reviewer's GO or
// NO-GO into a consensus, keep one summary comment per PR edited in place,
// set the Review consensus status, and set or clear the review-blocking label.
async function postTurn3({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  const { known, output } = readTurn(process.env.RELAY_OUTPUT, 'The moderator');
  const replies = validate(output, known, { maxReplies: 3, maxFindings: 0 }).replies;
  const impact = IMPACTS.includes(output.consensus_impact) ? output.consensus_impact : 'unclear';

  // The moderator reports turn 1 and the review apps; turn 2's own verdict
  // comes straight from its output, not through the moderator.
  const verdicts = (output.verdicts || [])
    .filter((v) => v && String(v.reviewer || '').trim() && VERDICTS.includes(v.verdict))
    .filter((v) => !/turn 2/i.test(v.reviewer))
    .slice(0, 10)
    .map((v) => ({
      reviewer: String(v.reviewer).trim(),
      verdict: v.verdict,
      // A refutation must say why, or it doesn't count.
      refuted: v.verdict === 'NO-GO' && v.refuted === true && Boolean(String(v.note || '').trim()),
      note: String(v.note || ''),
    }));
  const t2 = process.env.RELAY_TURN2_VERDICT;
  verdicts.push({
    reviewer: 'Relay turn 2 (second opinion)',
    verdict: VERDICTS.includes(t2) ? t2 : 'NONE',
    refuted: false,
    note: '',
  });
  const minGo = Number(process.env.RELAY_MIN_GO || 2);
  const { consensus, why, standing, gos } = tally(verdicts, minGo);
  const blocking = consensus !== 'GO';

  // What the PR needs before it can merge: the moderator's items, plus the
  // ones the tally implies, so a NO-GO always says how to get to GO.
  const needs = [];
  if (blocking) {
    needs.push(...(output.merge_needs || []).map((n) => String(n || '').trim()).filter(Boolean).slice(0, 10));
    // Every standing NO-GO must appear in the list: if the moderator's items
    // never name a reviewer (turn 2's verdict reaches the moderator only
    // through its prompt), add one for it.
    for (const v of standing) {
      const key = /turn 2/i.test(v.reviewer) ? /turn 2/i : new RegExp(v.reviewer.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
      if (!needs.some((n) => key.test(n))) {
        needs.push(`Resolve ${v.reviewer}'s NO-GO${v.note.trim() ? `: ${v.note.trim()}` : ' (see its review comments)'}.`);
      }
    }
    if (gos.length < minGo) needs.push(`At least ${minGo} reviewers must say GO (now ${gos.length}).`);
  }

  const table = [
    '| Reviewer | Verdict | Note |',
    '| --- | --- | --- |',
    ...verdicts.map((v) => `| ${cell(v.reviewer)} | ${v.refuted ? 'NO-GO, refuted' : v.verdict} | ${cell(v.note)} |`),
  ].join('\n');
  const state = [
    blocking
      ? `**Merge: no. Consensus: NO-GO** (${why}). What it needs before it can merge:\n\n${needs.map((n, i) => `${i + 1}. ${defuse(cap(n, 500))}`).join('\n')}\n`
      : `**Merge: yes. Consensus: GO** (${why}).`,
    `**Consensus impact:** ${impact}`,
    `**Determinism:** ${defuse(cap(output.determinism, 600)) || 'not assessed'}`,
    '',
    table,
    '',
    defuse(cap(output.summary_markdown, MAX_SUMMARY_CHARS)),
  ].join('\n');

  // Checked right before writing: an older run must not overwrite the
  // verdict for a newer commit.
  if (await headMoved(github, owner, repo, pr, headSha)) {
    core.info('A newer commit was pushed; turn 3 posts nothing for the old one.');
    return;
  }
  const posted = await postReplies(github, owner, repo, pr, 'turn 3 (moderator)', replies);

  const overridden = await hasOverride(github, owner, repo, pr);
  const turn2 = cap(process.env.RELAY_TURN2_SUMMARY, MAX_BODY_CHARS);
  const body = [
    RELAY_MARKER,
    headMarker(headSha),
    '## Review relay: state of the review',
    '',
    `_As of \`${headSha.slice(0, 7)}\`. Turn 1 is the Claude audit; turn 2 a second opinion that reads every reviewer; turn 3 this summary. It is edited in place on each push._`,
    '',
    state,
    turn2 ? `\n<details><summary>Turn 2 (second opinion)</summary>\n\n${defuse(turn2)}\n\n</details>` : '',
    '',
    overridden
      ? `_The \`${OVERRIDE_LABEL}\` label is on this PR, so the ${CONSENSUS_CONTEXT} check passes whatever the verdict. Remove it to restore the gate._`
      : `_GO means no reviewer has a standing objection. It is a gate, not an approval: the merge decision is the maintainer's, and the \`${OVERRIDE_LABEL}\` label overrides it._`,
    FOOTER,
  ].join('\n');

  const sticky = await findSticky(github, owner, repo, pr);
  if (sticky) {
    await github.rest.issues.updateComment({ owner, repo, comment_id: sticky.id, body });
  } else {
    await github.rest.issues.createComment({ owner, repo, issue_number: pr, body });
  }
  await setBlockingLabel(github, owner, repo, pr, blocking);
  await setRelayStatus(github, owner, repo, pr, headSha, blocking ? 'failure' : 'success',
    blocking ? `NO-GO, don't merge: ${needs.length} item(s) needed (see the relay summary)` : `GO, merge: ${why}`);
  core.info(`Turn 3: ${posted} replies; summary ${sticky ? 'updated' : 'created'}; consensus: ${consensus}.`);
}

// A relay job failed: the head gets no verdict, so say so instead of leaving
// the status pending.
async function reportFailure({ github, context }) {
  const { owner, repo } = context.repo;
  const pr = Number(process.env.RELAY_PR);
  const headSha = process.env.RELAY_HEAD_SHA;
  if (await headMoved(github, owner, repo, pr, headSha)) return;
  await setRelayStatus(github, owner, repo, pr, headSha, 'error', `Relay failed; re-run it, or a maintainer adds ${OVERRIDE_LABEL}`);
}

// The consensus-override label was added or removed. Only a person with
// write access can use it; anyone else's label is taken off again.
async function override({ github, context, core }) {
  const { owner, repo } = context.repo;
  const pr = context.payload.pull_request;
  if (!context.payload.label || context.payload.label.name !== OVERRIDE_LABEL) return;
  const sender = context.payload.sender && context.payload.sender.login;
  const allowed = await makeTrust(github, owner, repo)(sender, false);
  const added = context.payload.action === 'labeled';
  if (added && !allowed) {
    await github.rest.issues.removeLabel({ owner, repo, issue_number: pr.number, name: OVERRIDE_LABEL });
    core.warning(`${sender} has no write access; ${OVERRIDE_LABEL} removed.`);
    return;
  }
  if (added) {
    await setConsensus(github, owner, repo, pr.head.sha, 'success', `Overridden by ${sender}`);
    core.info(`${OVERRIDE_LABEL} added by ${sender}.`);
    return;
  }
  // Removed: go back to what the relay would say for this commit. A
  // docs-only PR passes without a relay run, as the gate does.
  if (await docsOnly(github, owner, repo, pr.number)) {
    await setConsensus(github, owner, repo, pr.head.sha, 'success', 'Docs-only change: the turn 1 audit covers it');
    core.info(`${OVERRIDE_LABEL} removed by ${sender}; docs-only PR passes.`);
    return;
  }
  const sticky = await findSticky(github, owner, repo, pr.number);
  const current = sticky && sticky.body.includes(headMarker(pr.head.sha));
  if (current && sticky.body.includes('Consensus: GO**')) {
    await setConsensus(github, owner, repo, pr.head.sha, 'success', `Override removed; the relay's verdict is GO`);
  } else {
    await setConsensus(github, owner, repo, pr.head.sha, 'failure',
      current ? `Override removed; the relay's verdict is NO-GO` : `Override removed by ${sender}; re-run the relay for a verdict`);
  }
  core.info(`${OVERRIDE_LABEL} removed by ${sender}.`);
}

module.exports = { gate, collect, postTurn2, postTurn3, reportFailure, override, validate, tally, clean, defuse, makeTrust, rightLines, tag, DOCS_ONLY };
