//! ONXBLK05 golden vectors: the Rust decoder/verifier must agree with the
//! Python reference (`reference/gen_auth_vectors.py`,
//! `reference/vectors/blockauth.json`, ADR-0032).
//!
//! This is the cross-implementation check: the vectors were generated by
//! the independent Python implementation; the Rust code must decode and
//! verify them byte-for-byte.

use onx::auth::{decode_sig_section, encode_sig_section, verify_block_auth, GenesisValidatorRef};
use onx::blockfile::{decode_block_file, BLOCK_FILE_MAGIC};
use onx_stf::block::{BlockHeader, BLOCK_HEADER_BYTE_LEN};
use std::collections::BTreeMap;

fn vectors() -> BTreeMap<String, serde_json::Value> {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../reference/vectors/blockauth.json"
    );
    let text = std::fs::read_to_string(path).expect("blockauth.json must exist");
    serde_json::from_str(&text).expect("blockauth.json must parse")
}

fn hex_val(v: &BTreeMap<String, serde_json::Value>, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().expect("hex string")).expect("valid hex")
}

#[test]
fn rust_decodes_python_header_byte_for_byte() {
    let v = vectors();
    let header_hex = hex_val(&v, "header_seq1_hex");
    assert_eq!(header_hex.len(), BLOCK_HEADER_BYTE_LEN);
    assert_eq!(header_hex.len(), 160);

    // Field offsets pinned by the vectors.
    let fields = v["header_fields"].as_object().unwrap();
    let seqno = &fields["seqno"];
    assert_eq!(seqno["offset"], 0);
    let pv = &fields["protocol_version"];
    assert_eq!(pv["offset"], 148);
    let bt = &fields["block_time"];
    assert_eq!(bt["offset"], 152);

    // Rust parses the Python-encoded header.
    let header = BlockHeader::from_bytes(&header_hex).expect("header parses");
    assert_eq!(header.seqno, 1);
    assert_eq!(header.protocol_version, 1);
    // Re-encode: byte-identical.
    assert_eq!(header.to_bytes(), header_hex);
}

#[test]
fn rust_recomputes_python_block_hash_and_preimage() {
    let v = vectors();
    let header_hex = hex_val(&v, "header_seq1_hex");
    let header = BlockHeader::from_bytes(&header_hex).unwrap();

    // block_hash = domain_hash(ONX_BLOCK_HDR_V1, header).
    assert_eq!(hex::encode(header.hash()), v["block_hash_seq1"]);

    // 96-byte signing preimage.
    let chain_id = [0xAAu8; 32];
    let preimage = header.sign_bytes(&chain_id);
    assert_eq!(preimage.len(), 96);
    assert_eq!(hex::encode(preimage), v["sign_preimage_seq1_hex"]);
    // Prefix is pad32("ONX_BLOCK_SIG_V1").
    assert_eq!(hex::encode(&preimage[..32]), v["sign_preimage_prefix_hex"]);
}

#[test]
fn rust_verifies_python_signature() {
    let v = vectors();
    let header_hex = hex_val(&v, "header_seq1_hex");
    let header = BlockHeader::from_bytes(&header_hex).unwrap();
    let sig_hex = hex_val(&v, "signature_seq1_hex");
    assert_eq!(sig_hex.len(), 64);

    let pubkey_hex = v["fixture_validator_pubkey"].as_str().unwrap();
    let mut pubkey = [0u8; 32];
    pubkey.copy_from_slice(&hex::decode(pubkey_hex).unwrap());
    let validators = [GenesisValidatorRef {
        pubkey,
        stake: 1000,
    }];

    let mut sig = [0u8; 64];
    sig.copy_from_slice(&sig_hex);
    let entries = vec![onx_stf::block::SigEntry {
        validator_index: 0,
        sig,
    }];

    let chain_id = [0xAAu8; 32];
    let stake = verify_block_auth(&chain_id, &header, 0, &entries, &validators)
        .expect("Python signature verifies");
    assert_eq!(stake, 1000);
}

#[test]
fn rust_decodes_python_sig_section() {
    let v = vectors();
    let sec_hex = hex_val(&v, "sig_section_hex");
    let entries = decode_sig_section(&sec_hex).expect("sig section decodes");
    assert_eq!(entries.len(), 1);
    assert_eq!(entries[0].validator_index, 0);
    // Re-encode: byte-identical.
    assert_eq!(encode_sig_section(&entries), sec_hex);
}

#[test]
fn rust_decodes_python_block_file() {
    let v = vectors();
    let file_hex = hex_val(&v, "block_file_seq1_hex");
    assert_eq!(&file_hex[..8], BLOCK_FILE_MAGIC);
    assert_eq!(v["block_file_magic"], "ONXBLK05");

    let signed = decode_block_file(&file_hex).expect("block file decodes");
    assert_eq!(signed.block.header.seqno, 1);
    assert_eq!(signed.sig_entries.len(), 1);
}

#[test]
fn rust_rejects_python_reject_vectors() {
    // The Python reference asserts these all raise; the Rust verifier must
    // fail closed on the same inputs. We test the Rust-side equivalents:
    // bad signature bytes, tampered header, unordered section.
    let v = vectors();
    let header_hex = hex_val(&v, "header_seq1_hex");
    let header = BlockHeader::from_bytes(&header_hex).unwrap();
    let pubkey_hex = v["fixture_validator_pubkey"].as_str().unwrap();
    let mut pubkey = [0u8; 32];
    pubkey.copy_from_slice(&hex::decode(pubkey_hex).unwrap());
    let validators = [GenesisValidatorRef {
        pubkey,
        stake: 1000,
    }];
    let chain_id = [0xAAu8; 32];

    // Bad signature (flipped bit).
    let mut bad_sig = hex_val(&v, "signature_seq1_hex");
    bad_sig[0] ^= 1;
    let mut sig = [0u8; 64];
    sig.copy_from_slice(&bad_sig);
    let entries = vec![onx_stf::block::SigEntry {
        validator_index: 0,
        sig,
    }];
    assert!(verify_block_auth(&chain_id, &header, 0, &entries, &validators).is_err());

    // Tampered header.
    let mut tampered = header_hex.clone();
    tampered[159] ^= 1;
    let th = BlockHeader::from_bytes(&tampered).unwrap();
    let mut sig2 = [0u8; 64];
    sig2.copy_from_slice(&hex_val(&v, "signature_seq1_hex"));
    let entries2 = vec![onx_stf::block::SigEntry {
        validator_index: 0,
        sig: sig2,
    }];
    assert!(verify_block_auth(&chain_id, &th, 0, &entries2, &validators).is_err());

    // Unordered sig section.
    let sec = encode_sig_section(&entries2);
    let mut dup = sec.clone();
    dup.extend_from_slice(&sec[4..]); // duplicate entry -> not strictly ascending
    assert!(decode_sig_section(&dup).is_err());
}

/// Helper: a valid header + entries from the golden vectors, with the
/// validator list the Python reference used.
fn golden_ok() -> (
    BlockHeader,
    Vec<onx_stf::block::SigEntry>,
    Vec<GenesisValidatorRef>,
    [u8; 32],
) {
    let v = vectors();
    let header = BlockHeader::from_bytes(&hex_val(&v, "header_seq1_hex")).unwrap();
    let mut sig = [0u8; 64];
    sig.copy_from_slice(&hex_val(&v, "signature_seq1_hex"));
    let entries = vec![onx_stf::block::SigEntry {
        validator_index: 0,
        sig,
    }];
    let pubkey_hex = v["fixture_validator_pubkey"].as_str().unwrap();
    let mut pubkey = [0u8; 32];
    pubkey.copy_from_slice(&hex::decode(pubkey_hex).unwrap());
    let validators = vec![GenesisValidatorRef {
        pubkey,
        stake: 1000,
    }];
    let chain_id = [0xAAu8; 32];
    (header, entries, validators, chain_id)
}

#[test]
fn auth_rejects_wrong_protocol_version() {
    let (mut header, entries, validators, chain_id) = golden_ok();
    header.protocol_version = 2;
    let err = verify_block_auth(&chain_id, &header, 0, &entries, &validators).unwrap_err();
    assert!(
        matches!(
            err,
            onx::auth::AuthError::UnsupportedProtocolVersion { got: 2 }
        ),
        "expected UnsupportedProtocolVersion, got: {err}"
    );
}

#[test]
fn auth_rejects_block_time_regression() {
    let (header, entries, validators, chain_id) = golden_ok();
    // Golden block_time is 0x6ab13b80; a parent ahead of it must fail.
    let parent = header.block_time + 1;
    let err = verify_block_auth(&chain_id, &header, parent, &entries, &validators).unwrap_err();
    assert!(
        matches!(err, onx::auth::AuthError::BlockTimeRegression { .. }),
        "expected BlockTimeRegression, got: {err}"
    );
    // Equal is fine (monotonic = non-decreasing).
    verify_block_auth(&chain_id, &header, header.block_time, &entries, &validators)
        .expect("equal block_time is monotonic");
}

#[test]
fn auth_rejects_unordered_indices_directly() {
    // Defense in depth: verify_block_auth must reject unordered indices
    // even when called directly, bypassing decode_sig_section.
    let (header, entries, validators, chain_id) = golden_ok();
    let mut two = vec![entries[0].clone(), entries[0].clone()]; // duplicate index 0
    two[1].validator_index = 0;
    let err = verify_block_auth(&chain_id, &header, 0, &two, &validators).unwrap_err();
    assert!(
        matches!(err, onx::auth::AuthError::UnorderedIndices),
        "expected UnorderedIndices, got: {err}"
    );
}
