//! Cell bit-length agreement: the Rust implementation (`Cell::new_with_bit_len`,
//! `Cell::from_bytes`, `Builder::append_bytes`, `Slice::remaining_bits` —
//! ADR-0036) must agree with the independent Python reference
//! (`reference/gen_bitlen_vectors.py`, `reference/vectors/bitlen.json`).
//!
//! This is the cross-implementation check: the vectors were generated by the
//! Python model written from the spec text; the Rust code must produce
//! byte-identical results. Interpreter opcode wiring (ENDC/STBYTES/SBITS) is
//! covered by unit tests in `types.rs`/`cell.rs` and the execution suite.

use onx_execution::Builder;
use onx_state_model::Cell;
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../reference/vectors/bitlen.json"
    );
    let text = std::fs::read_to_string(path).expect("bitlen.json must exist");
    serde_json::from_str(&text).expect("bitlen.json must parse")
}

fn hex_bytes(v: &Value, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().expect("hex string")).expect("valid hex")
}

#[test]
fn finalize_agrees_with_python() {
    let v = vectors();
    assert_eq!(v["adr"].as_str(), Some("ADR-0036"));
    for case in v["finalize"].as_array().expect("finalize array") {
        let data = hex_bytes(case, "data_hex");
        let bit_len = case["bit_len_in"].as_u64().expect("bit_len") as usize;
        let refs: Vec<[u8; 32]> = case["refs_hex"]
            .as_array()
            .expect("refs_hex")
            .iter()
            .map(|r| {
                let b = hex::decode(r.as_str().unwrap()).unwrap();
                let mut arr = [0u8; 32];
                arr.copy_from_slice(&b);
                arr
            })
            .collect();
        let cell = Cell::new_with_bit_len(data, bit_len, refs).unwrap_or_else(|e| {
            panic!(
                "finalize({:?}, {}) failed in Rust: {:?}",
                case["data_hex"], bit_len, e
            )
        });
        assert_eq!(
            cell.data_bytes(),
            &hex_bytes(case, "tagged_data_hex")[..],
            "tagged data for {:?}/{}",
            case["data_hex"],
            bit_len
        );
        assert_eq!(
            cell.is_bit_granular(),
            case["bit_granular"].as_bool().unwrap(),
            "flag for {:?}/{}",
            case["data_hex"],
            bit_len
        );
        let (d1, d2) = cell.descriptor_bytes();
        assert_eq!(
            &[d1, d2],
            &hex_bytes(case, "descriptor_hex")[..],
            "descriptor for {:?}/{}",
            case["data_hex"],
            bit_len
        );
        assert_eq!(
            cell.bit_len(),
            case["bit_len_out"].as_u64().unwrap() as usize,
            "bit_len for {:?}/{}",
            case["data_hex"],
            bit_len
        );
        assert_eq!(
            cell.hash(),
            hex_bytes(case, "hash_hex")[..],
            "hash for {:?}/{}",
            case["data_hex"],
            bit_len
        );
    }
}

#[test]
fn decode_reject_agrees_with_python() {
    let v = vectors();
    for case in v["decode_reject"].as_array().expect("decode_reject array") {
        assert_eq!(
            case["status"].as_str(),
            Some("rejected"),
            "Python model must reject its own reject vector {:?}",
            case["encoding_hex"]
        );
        let enc = hex_bytes(case, "encoding_hex");
        assert!(
            Cell::from_bytes(&enc).is_err(),
            "Rust must reject {:?} ({})",
            case["encoding_hex"],
            case["rule"].as_str().unwrap_or("?")
        );
    }
}

#[test]
fn decode_accept_agrees_with_python() {
    let v = vectors();
    for case in v["decode_accept"].as_array().expect("decode_accept array") {
        let enc = hex_bytes(case, "encoding_hex");
        let (cell, consumed) = Cell::from_bytes(&enc).unwrap_or_else(|e| {
            panic!(
                "Rust rejected canonical {:?}: {:?}",
                case["encoding_hex"], e
            )
        });
        assert_eq!(consumed, enc.len());
        assert_eq!(
            cell.is_bit_granular(),
            case["bit_granular"].as_bool().unwrap(),
            "flag for {:?}",
            case["encoding_hex"]
        );
        assert_eq!(
            cell.bit_len(),
            case["bit_len"].as_u64().unwrap() as usize,
            "bit_len for {:?}",
            case["encoding_hex"]
        );
        assert_eq!(
            cell.hash(),
            hex_bytes(case, "hash_hex")[..],
            "hash for {:?}",
            case["encoding_hex"]
        );
    }
}

#[test]
fn builder_append_agrees_with_python() {
    let v = vectors();
    for case in v["builder_append"]
        .as_array()
        .expect("builder_append array")
    {
        // The vector start states are (data, bit_len) pairs the Python model
        // itself produces, so they satisfy the builder invariant; construct
        // the Rust builder in exactly that state via its public fields.
        let mut builder = Builder {
            data_bytes: hex_bytes(case, "start_data_hex"),
            current_bit_len: case["start_bit_len"].as_u64().unwrap() as usize,
            references: Vec::new(),
        };
        let append = hex_bytes(case, "append_hex");
        let result = builder.append_bytes(&append);
        let label = format!(
            "append {:?} to ({:?}, {})",
            case["append_hex"], case["start_data_hex"], case["start_bit_len"]
        );
        match case.get("ok").and_then(|o| o.as_bool()) {
            Some(true) => {
                result.unwrap_or_else(|e| panic!("{} failed in Rust: {:?}", label, e));
                assert_eq!(
                    builder.data_bytes,
                    hex_bytes(case, "data_hex")[..],
                    "{}: data",
                    label
                );
                assert_eq!(
                    builder.current_bit_len,
                    case["bit_len"].as_u64().unwrap() as usize,
                    "{}: bit_len",
                    label
                );
            }
            _ => {
                assert!(
                    result.is_err(),
                    "{}: Rust must fail closed like the model",
                    label
                );
                assert_eq!(
                    case.get("error").and_then(|e| e.as_str()),
                    Some("MalformedCell"),
                    "{}: model error kind",
                    label
                );
            }
        }
    }
}

#[test]
fn slice_remaining_bits_agrees_with_python() {
    let v = vectors();
    for case in v["slice_remaining"]
        .as_array()
        .expect("slice_remaining array")
    {
        let label = case["cell"].as_str().unwrap().to_string();
        let cell = if label.starts_with("finalize(") {
            let inner = &label["finalize(".len()..label.len() - 1];
            let mut parts = inner.split(',');
            let data = hex::decode(parts.next().unwrap()).unwrap();
            let bit_len: usize = parts.next().unwrap().parse().unwrap();
            Cell::new_with_bit_len(data, bit_len, Vec::new()).expect("finalize builds")
        } else {
            let enc_hex = &label["decode(".len()..label.len() - 1];
            let enc = hex::decode(enc_hex).unwrap();
            Cell::from_bytes(&enc).expect("decode accepts").0
        };
        let offset = case["bit_offset"].as_u64().unwrap() as usize;
        let remaining = cell.bit_len().saturating_sub(offset);
        assert_eq!(
            remaining,
            case["remaining_bits"].as_u64().unwrap() as usize,
            "{} @ offset {}",
            label,
            offset
        );
    }
}
