//! Chain-bound CHKSIGNU agreement: the Rust implementation
//! (`DomainTag::bind_chain`, `CHKSIGNU_V1`, and the interpreter's 0x62
//! verification path — ADR-0038) must agree with the independent Python
//! reference (`reference/gen_chksignu_vectors.py`,
//! `reference/vectors/chksignu.json`).
//!
//! This is the cross-implementation check: the vectors were generated by the
//! Python model written from the spec text; the Rust code must produce
//! byte-identical tags and accept/reject the same signatures. The two
//! replay attacks from Claude's finding are pinned as negatives:
//! cross-chain (chain A signature under chain B's tag) and cross-protocol
//! (retired TX_BODY_V1 signature under the CHKSIGNU tag).

use onx_primitives::hash::{DomainTag, CHKSIGNU_V1};
use onx_primitives::{PublicKey, Signature};
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../reference/vectors/chksignu.json"
    );
    let text = std::fs::read_to_string(path).expect("chksignu.json must exist");
    serde_json::from_str(&text).expect("chksignu.json must parse")
}

fn hex32(v: &Value, key: &str) -> [u8; 32] {
    let b = hex::decode(v[key].as_str().expect("hex string")).expect("valid hex");
    b.as_slice().try_into().expect("32 bytes")
}

fn hex_bytes(v: &Value, key: &str) -> Vec<u8> {
    hex::decode(v[key].as_str().expect("hex string")).expect("valid hex")
}

#[test]
fn tag_derivation_agrees_with_python() {
    let v = vectors();
    assert_eq!(v["adr"].as_str(), Some("ADR-0038"));
    assert_eq!(v["chksignu_base"].as_str(), Some("ONX_CHKSIGNU_V1"));
    for case in v["tag_vectors"].as_array().expect("tag_vectors array") {
        let chain_id = hex32(case, "chain_id_hex");
        let expected = hex32(case, "derived_tag_hex");
        let derived = CHKSIGNU_V1.bind_chain(&chain_id);
        assert_eq!(
            derived.as_bytes(),
            &expected,
            "bind_chain mismatch for chain_id {}",
            case["chain_id_hex"].as_str().unwrap()
        );
    }
}

#[test]
fn signatures_verify_under_correct_chain_tag() {
    let v = vectors();
    for case in v["signatures"].as_array().expect("signatures array") {
        let chain_id = hex32(case, "chain_id_hex");
        let hash32 = hex32(case, "hash32_hex");
        let pubkey_bytes = hex_bytes(case, "pubkey_hex");
        let sig_bytes = hex_bytes(case, "sig_hex");
        let tag = CHKSIGNU_V1.bind_chain(&chain_id);
        let pubkey = PublicKey::decode_exact(&pubkey_bytes).expect("valid pubkey bytes");
        let sig = Signature::decode_exact(&sig_bytes).expect("valid sig bytes");
        assert!(
            pubkey.verify(&tag, &hash32, &sig).is_ok(),
            "oracle signature must verify under its chain's tag"
        );
    }
}

#[test]
fn cross_chain_replay_does_not_verify() {
    // The exact attack from the finding: a signature produced for chain A
    // must not verify when checked against chain B's tag.
    let v = vectors();
    for case in v["cross_chain_negatives"]
        .as_array()
        .expect("cross_chain_negatives array")
    {
        let chain_id = hex32(case, "chain_id_hex");
        let hash32 = hex32(case, "hash32_hex");
        let pubkey_bytes = hex_bytes(case, "pubkey_hex");
        let sig_bytes = hex_bytes(case, "sig_hex");
        let tag = CHKSIGNU_V1.bind_chain(&chain_id);
        let pubkey = PublicKey::decode_exact(&pubkey_bytes).expect("valid pubkey bytes");
        let sig = Signature::decode_exact(&sig_bytes).expect("valid sig bytes");
        assert!(
            pubkey.verify(&tag, &hash32, &sig).is_err(),
            "cross-chain replay must NOT verify"
        );
    }
}

#[test]
fn cross_protocol_replay_does_not_verify() {
    // The exact pre-ADR-0038 attack: a payment-channel-style signature made
    // under the retired TX_BODY_V1 tag must not verify as a CHKSIGNU
    // signature.
    let v = vectors();
    for case in v["cross_protocol_negatives"]
        .as_array()
        .expect("cross_protocol_negatives array")
    {
        let chain_id = hex32(case, "chain_id_hex");
        let hash32 = hex32(case, "hash32_hex");
        let pubkey_bytes = hex_bytes(case, "pubkey_hex");
        let sig_bytes = hex_bytes(case, "sig_hex");
        let tag = CHKSIGNU_V1.bind_chain(&chain_id);
        let pubkey = PublicKey::decode_exact(&pubkey_bytes).expect("valid pubkey bytes");
        let sig = Signature::decode_exact(&sig_bytes).expect("valid sig bytes");
        assert!(
            pubkey.verify(&tag, &hash32, &sig).is_err(),
            "TX_BODY_V1 signature must NOT verify as CHKSIGNU"
        );
    }
}

#[test]
fn base_tag_is_never_used_raw() {
    // Defense-in-depth: the base tag alone must not equal any derived tag,
    // so code that accidentally uses CHKSIGNU_V1 raw fails closed rather
    // than verifying cross-chain.
    let v = vectors();
    for case in v["tag_vectors"].as_array().expect("tag_vectors array") {
        let chain_id = hex32(case, "chain_id_hex");
        let derived = CHKSIGNU_V1.bind_chain(&chain_id);
        assert_ne!(
            derived, CHKSIGNU_V1,
            "derived tag must never equal the raw base tag"
        );
        // And the retired tag's padded bytes are not a derived tag either.
        let retired = DomainTag::from_ascii("ONX_TX_BODY_V1");
        assert_ne!(derived, retired, "derived tag must not equal TX_BODY_V1");
    }
}

// ---------------------------------------------------------------------------
// VM-level integration: CHKSIGNU through the actual 0x62 opcode.

use onx_data_structures::{AccountId, FullAddress, Message, MessageType, WorkchainIdent};
use onx_execution::{ExecutionContext, ExecutionResult, Int257, StackValue};
use onx_primitives::SecretKey;
use onx_state_model::Cell;

fn vm_message() -> Message {
    let addr = FullAddress::new(WorkchainIdent::BASIC, AccountId::from_bytes([0x01; 32]));
    Message {
        msg_type: MessageType::Internal,
        src_address: addr,
        dest_address: addr,
        amount_nanos: onx_primitives::Uint128::from(1000u128),
        extra_currencies: vec![],
        created_lt: onx_primitives::Uint64::from(100u64),
        body_cell_hash: onx_primitives::Uint256([0xAA; 32]),
    }
}

fn vm_context(chain_id: [u8; 32]) -> ExecutionContext {
    ExecutionContext {
        gen_utime: 1700000000,
        start_lt: 100,
        end_lt: 200,
        gas_limit: 100_000,
        chain_id,
    }
}

/// Builds minimal bytecode: CHKSIGNU, RET. The stack is pre-loaded by the
/// test (cells cap code at 128 bytes; the operands don't fit as inline
/// PUSHBYTES).
fn chksignu_program() -> Vec<u8> {
    vec![0x62, 0x72] // CHKSIGNU, RET
}

fn run_chksignu(chain_id: [u8; 32], pubkey: &[u8], sig: &[u8], hash32: &[u8; 32]) -> i64 {
    let code = Cell::new(chksignu_program(), vec![]).expect("program fits in a cell");
    let data = Cell::new(vec![], vec![]).expect("empty cell");
    let mut interp =
        onx_execution::Interpreter::new(code, data, vm_message(), vm_context(chain_id));
    // Stack (bottom→top): pubkey, signature, hash — matching 0x62's pop order.
    interp.stack.push(StackValue::Bytes(pubkey.to_vec()));
    interp.stack.push(StackValue::Bytes(sig.to_vec()));
    interp
        .stack
        .push(StackValue::Integer(Int257::from_unsigned256(hash32)));
    match interp.run() {
        ExecutionResult::Success { .. } => match interp.stack.last() {
            Some(StackValue::Integer(i)) if *i == Int257::from_u64(1) => 1,
            Some(StackValue::Integer(i)) if i.is_zero() => 0,
            other => panic!("unexpected stack top: {:?}", other),
        },
        ExecutionResult::Exception { kind, .. } => panic!("unexpected exception: {:?}", kind),
    }
}

#[test]
fn chksignu_opcode_verifies_with_correct_chain_id() {
    let chain_id = [0x43; 32];
    let hash32 = [0x07; 32];
    let sk = SecretKey::from_seed(&[0x11; 32]).expect("seed");
    let tag = CHKSIGNU_V1.bind_chain(&chain_id);
    let sig = sk.sign(&tag, &hash32);
    let pubkey = sk.public_key();
    assert_eq!(
        run_chksignu(chain_id, &pubkey.encode(), &sig.encode(), &hash32),
        1,
        "valid signature must verify through the opcode"
    );
}

#[test]
fn chksignu_opcode_rejects_wrong_chain_id() {
    // The VM-level cross-chain replay: signature made for chain A, executed
    // with chain B's context — the opcode must push 0, not raise.
    let chain_a = [0x43; 32];
    let chain_b = [0x44; 32];
    let hash32 = [0x07; 32];
    let sk = SecretKey::from_seed(&[0x11; 32]).expect("seed");
    let tag_a = CHKSIGNU_V1.bind_chain(&chain_a);
    let sig = sk.sign(&tag_a, &hash32);
    let pubkey = sk.public_key();
    assert_eq!(
        run_chksignu(chain_b, &pubkey.encode(), &sig.encode(), &hash32),
        0,
        "cross-chain signature must NOT verify through the opcode"
    );
}
