//! 257-bit integer model agreement: the Rust implementation (`int257.rs`,
//! ADR-0035) must agree with the independent Python reference
//! (`reference/gen_int257_vectors.py`, `reference/vectors/int257.json`).
//!
//! This is the cross-implementation check: the vectors were generated by
//! the Python model written from the spec text; the Rust code must produce
//! byte-identical results. The interpreter wiring (operand loading,
//! exception kinds) is covered separately by `tests/arithmetic_safety.rs`;
//! this test drives the same model functions the interpreter calls.

use onx_execution::{ExceptionKind, Int257};
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../reference/vectors/int257.json"
    );
    let text = std::fs::read_to_string(path).expect("int257.json must exist");
    serde_json::from_str(&text).expect("int257.json must parse")
}

/// A vector value: canonical 33-byte big-endian hex.
fn parse_int(v: &Value) -> Int257 {
    let hex33 = v["hex33"].as_str().expect("hex33 string");
    let bytes = hex::decode(hex33).expect("valid hex");
    assert_eq!(bytes.len(), 33, "canonical 257-bit encoding");
    let mut arr = [0u8; 33];
    arr.copy_from_slice(&bytes);
    Int257::from_bytes33(&arr).expect("canonical encoding")
}

fn expect_error(v: &Value) -> bool {
    v.get("error")
        .map(|e| e == "IntegerOverflow")
        .unwrap_or(false)
}

/// Runs one vector case through the Rust model, returning the produced
/// value(s) or the `ExceptionKind`.
fn run_case(case: &Value) -> Result<Vec<Int257>, ExceptionKind> {
    let op = case["op"].as_str().expect("op");
    let width = case["width"].as_u64().expect("width") as u16;
    let flavor = case["flavor"].as_u64().expect("flavor") as u8;
    let a = parse_int(&case["a"]);
    match op {
        "add" => {
            let b = parse_int(&case["b"]);
            Ok(vec![a.add_exact(b).apply(width, flavor)?])
        }
        "sub" => {
            let b = parse_int(&case["b"]);
            Ok(vec![a.sub_exact(b).apply(width, flavor)?])
        }
        "mul" => {
            let b = parse_int(&case["b"]);
            Ok(vec![a.mul_exact(b).apply(width, flavor)?])
        }
        "neg" => Ok(vec![a.neg_exact().apply(width, flavor)?]),
        "conv" => Ok(vec![a.check_width(width, flavor)?]),
        "div" => {
            let b = parse_int(&case["b"]);
            let (q, _) =
                Int257::floored_divmod_exact(a, b).ok_or(ExceptionKind::IntegerOverflow)?;
            Ok(vec![q.apply(width, flavor)?])
        }
        "divmod" => {
            let b = parse_int(&case["b"]);
            let (q, r) =
                Int257::floored_divmod_exact(a, b).ok_or(ExceptionKind::IntegerOverflow)?;
            Ok(vec![q.apply(width, flavor)?, r.apply(width, flavor)?])
        }
        "lshift" | "rshift" => {
            let b = parse_int(&case["b"]);
            // The interpreter's range check, replicated: shift amounts that
            // are negative or >= width raise before flavor selection.
            let shift = b
                .to_usize_checked()
                .filter(|&s| s < width as usize)
                .ok_or(ExceptionKind::IntegerOverflow)?;
            if op == "lshift" {
                Ok(vec![a.shl_exact(shift as u32).apply(width, flavor)?])
            } else {
                Ok(vec![a
                    .shr_exact(shift as u32)
                    .check_width(width, flavor)?])
            }
        }
        _ => panic!("unknown op {op}"),
    }
}

#[test]
fn rust_agrees_with_python_on_every_vector() {
    let v = vectors();
    assert_eq!(v["integer_bits"], 257);
    let cases = v["cases"].as_array().expect("cases array");
    assert!(!cases.is_empty());
    let mut wrong = Vec::new();
    let mut errors = 0usize;
    for (i, case) in cases.iter().enumerate() {
        let got = run_case(case);
        let want_is_error = expect_error(&case["result"]);
        match (got, want_is_error) {
            (Err(ExceptionKind::IntegerOverflow), true) => {
                errors += 1;
            }
            (Err(e), true) => {
                wrong.push(format!(
                    "case {i}: wrong error kind {e:?}, want IntegerOverflow"
                ));
            }
            (Err(e), false) => {
                wrong.push(format!(
                    "case {i}: unexpected {e:?}, want {}",
                    case["result"]
                ));
            }
            (Ok(_), true) => {
                wrong.push(format!("case {i}: expected IntegerOverflow, got success"));
            }
            (Ok(vals), false) => {
                let want_vals: Vec<Int257> = if case["op"] == "divmod" {
                    vec![
                        parse_int(&case["result"]["q"]),
                        parse_int(&case["result"]["r"]),
                    ]
                } else {
                    vec![parse_int(&case["result"])]
                };
                if vals != want_vals {
                    wrong.push(format!(
                        "case {i} ({}): got {:?}, want {:?}",
                        case["op"], vals, want_vals
                    ));
                }
            }
        }
        if wrong.len() >= 10 {
            break;
        }
    }
    assert!(
        wrong.is_empty(),
        "{} mismatches ({} error cases), e.g.:\n{}",
        wrong.len(),
        errors,
        wrong.join("\n")
    );
    // The corpus must contain both outcomes, or the agreement is vacuous.
    assert!(errors > 0, "no IntegerOverflow cases in the corpus");
    assert!(cases.len() > errors, "corpus has no success cases");
}
